version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/alecthomas/kong-yaml
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.32.2
          when: always
      - run:
          name: Test
          command: |
            go test -v ./...
      - run:
          name: Lint
          command: |
            ./bin/golangci-lint run
